export const MONTHS_FULL  = ['January','February','March','April','May','June','July','August','September','October','November','December'];
export const MONTHS_SHORT = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

export const styles = {
  page:           'flex-1 overflow-auto bg-[#F4F5F7] p-6',
  pageHeader:     'flex items-center justify-between mb-6',
  pageTitle:      'text-lg font-semibold text-gray-800',
  pageSubtitle:   'text-sm text-gray-400',
  filterRow:      'flex items-center gap-2',
  filterLabel:    'text-xs text-gray-500 whitespace-nowrap',
  filterSelect:   'border border-gray-200 rounded-xl px-3 py-1.5 text-sm text-gray-700 outline-none',
  spinner:        'flex items-center justify-center h-64',
  spinnerEl:      'w-10 h-10 border-4 border-gray-200 border-t-[#1C1C2E] rounded-full animate-spin',
  statGrid:       'grid grid-cols-3 gap-4 mb-6 items-start',
  card:           'bg-white rounded-2xl p-4 shadow-sm border border-gray-100',
  cardLabel:      'text-xs font-semibold text-gray-400 uppercase tracking-wider mb-1.5',
  cardValueGray:  'text-2xl font-bold text-gray-800',
  cardValueOrange:'text-2xl font-bold text-orange-500',
  cardValueGreen: 'text-2xl font-bold text-green-600',
  cardMeta:       'text-xs text-gray-400 mt-1',
  chartsGrid:     'grid grid-cols-2 gap-4 mb-6',
  cardTitle:      'text-sm font-semibold text-gray-700 mb-5',
  barChart:       'flex items-end gap-3 h-44 px-2',
  barCol:         'flex-1 flex flex-col items-center gap-1.5',
  barLabel:       'text-[10px] text-gray-400 font-medium',
  barEl:          'w-full rounded-t-xl bg-violet-500 transition-all duration-500',
  barWeekLabel:   'text-[10px] text-gray-400',
  supplierList:   'flex flex-col gap-4 overflow-y-auto max-h-72',
  supplierRow:    'flex justify-between text-xs text-gray-600 mb-1.5',
  supplierName:   'truncate max-w-[65%] font-medium',
  supplierRev:    'font-semibold',
  supplierBar:    'h-2 bg-gray-100 rounded-full overflow-hidden',
  supplierFill:   'h-full bg-violet-500 rounded-full transition-all duration-500',
  topCustTh:      'py-2.5 text-left text-xs font-semibold text-gray-400 uppercase tracking-wide',
  topCustRow:     'border-b border-gray-50 hover:bg-violet-50/40 transition-colors',
  topCustRank:    'py-3 text-gray-400 text-xs font-medium',
  topCustName:    'py-3 font-medium text-gray-800',
  topCustOrders:  'py-3 text-gray-600',
  topCustAmount:  'py-3 font-semibold text-gray-800',
};
