export const styles = {
  toolbarWrap:       'flex items-center justify-between gap-2 px-6 py-2 border-b border-gray-100 bg-white',
  searchInput:       'border border-gray-200 rounded-xl px-3 py-1.5 text-sm text-gray-700 outline-none w-56',
  filterGroup:       'flex items-center gap-2 ml-auto',
  filterTabs:        'flex items-center rounded-xl border border-gray-200 overflow-hidden text-xs font-medium',
  filterBtnBase:     'px-3 py-1.5 transition-colors whitespace-nowrap',
  filterBtnAdmin:    'bg-violet-600 text-white',
  filterBtnSupplier: 'bg-blue-500 text-white',
  filterBtnUser:     'bg-teal-500 text-white',
  filterBtnAll:      'bg-[#1C1C2E] text-white',
  filterBtnDefault:  'text-gray-500 hover:bg-gray-50',
  filterBtnActive:   'bg-green-500 text-white',
  filterBtnInactive: 'bg-yellow-500 text-white',
  roleCell:          'text-xs px-2.5 py-1 rounded-full bg-gray-100 text-gray-600 font-medium',
  activeStatus:      'text-xs px-2.5 py-1 rounded-full bg-green-50 text-green-600 border border-green-200 font-medium',
  inactiveStatus:    'text-xs px-2.5 py-1 rounded-full bg-red-50 text-red-500 border border-red-200 font-medium',
  joinedCell:        'px-4 py-3 text-gray-500 text-xs',
  // UpdateUserModal
  modalRolesLabel:   'text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2 block',
  roleGrid:          'grid grid-cols-2 gap-2',
  roleLabel:         'flex items-center gap-2 select-none',
  roleCheckbox:      'w-4 h-4 rounded accent-violet-500',
  roleText:          'text-sm text-gray-700',
  statusBtnActive:   'flex-1 py-2 text-sm rounded-xl border transition-colors bg-green-500 text-white border-green-500',
  statusBtnInactive: 'flex-1 py-2 text-sm rounded-xl border transition-colors bg-red-500 text-white border-red-500',
  statusBtnDefault:  'flex-1 py-2 text-sm rounded-xl border transition-colors border-gray-200 text-gray-600 hover:bg-gray-50',
};
