export const STATUS_CONFIG = {
  ORDERED:   { label: 'Ordered',   cls: 'bg-blue-100 text-blue-700' },
  PAYMENT:   { label: 'Payment',   cls: 'bg-yellow-100 text-yellow-700' },
  CONFIRMED: { label: 'Confirmed', cls: 'bg-purple-100 text-purple-700' },
  DELIVERED: { label: 'Delivered', cls: 'bg-green-100 text-green-700' },
  CANCELLED: { label: 'Cancelled', cls: 'bg-red-100 text-red-700' },
};

export const STATUS_BAR_COLORS = {
  ORDERED:   'bg-blue-400',
  PAYMENT:   'bg-yellow-400',
  CONFIRMED: 'bg-purple-500',
  DELIVERED: 'bg-green-500',
  CANCELLED: 'bg-red-400',
};

export const styles = {
  loadingWrapper:    'min-h-screen bg-gray-100 flex items-center justify-center',
  spinner:           'w-10 h-10 border-4 border-gray-300 border-t-green-600 rounded-full animate-spin',
  page:              'min-h-screen bg-gray-200 py-8 px-4 print:bg-white print:p-0',
  printBar:          'flex justify-center mb-6 print:hidden',
  printBtn:          'flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white text-sm font-semibold px-6 py-2.5 rounded-lg shadow transition-colors',
  card:              'bg-white w-full max-w-5xl mx-auto shadow-xl rounded-lg overflow-hidden print:shadow-none print:rounded-none print:max-w-none',
  header:            'bg-green-700 px-8 py-6 text-white',
  headerTitle:       'text-2xl font-bold tracking-tight',
  headerSubtitle:    'text-green-200 text-sm mt-1',
  headerMeta:        'flex gap-8 mt-4 text-sm',
  headerMetaLabel:   'text-green-300 text-xs uppercase tracking-wide',
  headerMetaValue:   'font-semibold',
  body:              'px-8 py-6 space-y-6',
  sectionLabel:      'text-xs font-bold text-gray-400 uppercase tracking-widest mb-3',
  summaryGrid:       'grid grid-cols-4 gap-3',
  summaryCardBlue:   'border border-gray-100 rounded-xl p-4 bg-blue-50',
  summaryCardPurple: 'border border-gray-100 rounded-xl p-4 bg-purple-50',
  summaryCardGreen:  'border border-gray-100 rounded-xl p-4 bg-green-50',
  summaryCardRed:    'border border-gray-100 rounded-xl p-4 bg-red-50',
  summaryLabelBlue:  'text-xs font-semibold text-blue-400 uppercase mb-1',
  summaryLabelPurple:'text-xs font-semibold text-purple-400 uppercase mb-1',
  summaryLabelGreen: 'text-xs font-semibold text-green-500 uppercase mb-1',
  summaryLabelRed:   'text-xs font-semibold text-red-400 uppercase mb-1',
  summaryValueBlue:  'text-2xl font-bold text-blue-600',
  summaryValuePurple:'text-2xl font-bold text-purple-600',
  summaryValueGreen: 'text-2xl font-bold text-green-600',
  summaryValueRed:   'text-2xl font-bold text-red-500',
  distBox:           'border border-gray-100 rounded-xl p-4',
  distBar:           'flex h-6 rounded-full overflow-hidden gap-0.5',
  distBarSegment:    'flex items-center justify-center text-white text-[10px] font-bold',
  distLegend:        'flex flex-wrap gap-3 mt-3',
  distBadge:         'inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold',
  tableWrapper:      'border border-gray-100 rounded-xl overflow-hidden',
  thead:             'bg-gray-50',
  th:                'px-2 py-2 text-left font-bold text-gray-400 uppercase tracking-wide',
  rowEven:           'bg-white',
  rowOdd:            'bg-gray-50',
  tdRank:            'px-2 py-2 text-gray-400 font-bold',
  tdOrderNo:         'px-2 py-2 font-mono text-gray-600 break-all',
  tdCustomer:        'px-2 py-2 font-medium text-gray-800',
  tdItem:            'px-2 py-2 text-gray-500',
  tdAmount:          'px-2 py-2 font-bold text-gray-800 whitespace-nowrap',
  tdDate:            'px-2 py-2 text-gray-400 whitespace-nowrap',
  statusBadge:       'inline-block px-1.5 py-0.5 rounded-full font-semibold',
  emptyCell:         'px-4 py-8 text-center text-gray-400 text-sm',
  footer:            'border-t border-gray-100 pt-4 text-center text-xs text-gray-300',
};
