export const styles = {
  loadingWrapper:      'min-h-screen bg-gray-100 flex items-center justify-center',
  spinner:             'w-10 h-10 border-4 border-gray-300 border-t-indigo-600 rounded-full animate-spin',
  page:                'min-h-screen bg-gray-200 py-8 px-4 print:bg-white print:p-0 print:py-0',
  printBar:            'flex justify-center mb-6 print:hidden',
  printBtn:            'flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-semibold px-6 py-2.5 rounded-lg shadow transition-colors',
  card:                'bg-white w-full max-w-3xl mx-auto shadow-xl rounded-lg overflow-hidden print:shadow-none print:rounded-none print:max-w-none',
  header:              'bg-indigo-600 px-8 py-6 text-white',
  headerTitle:         'text-2xl font-bold tracking-tight',
  headerSubtitle:      'text-indigo-200 text-sm mt-1',
  headerMeta:          'flex gap-8 mt-4 text-sm',
  headerMetaLabel:     'text-indigo-300 text-xs uppercase tracking-wide',
  headerMetaValue:     'font-semibold',
  body:                'px-8 py-6 space-y-8',
  sectionLabel:        'text-xs font-bold text-gray-400 uppercase tracking-widest mb-3',
  statGrid:            'grid grid-cols-3 gap-4',
  statCardBlue:        'border border-gray-100 rounded-xl p-4 bg-blue-50',
  statLabelBlue:       'text-xs font-semibold text-blue-400 uppercase tracking-wide mb-2',
  statValueBlue:       'text-3xl font-bold text-blue-700',
  statMetaBlue:        'text-xs text-blue-400 mt-1',
  statCardOrange:      'border border-gray-100 rounded-xl p-4 bg-orange-50',
  statLabelOrange:     'text-xs font-semibold text-orange-400 uppercase tracking-wide mb-2',
  statValueOrange:     'text-3xl font-bold text-orange-500',
  statMetaOrange:      'text-xs text-orange-400 mt-1',
  statCardGreen:       'border border-gray-100 rounded-xl p-4 bg-green-50',
  statLabelGreen:      'text-xs font-semibold text-green-500 uppercase tracking-wide mb-2',
  statValueGreen:      'text-2xl font-bold text-green-600',
  statMetaGreen:       'text-xs text-green-400 mt-1',
  chartBox:            'border border-gray-100 rounded-xl p-5',
  chartBars:           'flex items-end gap-4 h-40',
  chartBarCol:         'flex-1 flex flex-col items-center gap-1.5',
  chartBarLabel:       'text-[10px] text-gray-500 font-medium text-center leading-tight',
  chartBarWeek:        'text-[10px] text-gray-400 font-medium',
  supplierBox:         'border border-gray-100 rounded-xl p-5',
  supplierEmpty:       'text-sm text-gray-400 text-center py-4',
  supplierList:        'space-y-4',
  supplierRow:         'flex justify-between text-xs text-gray-600 mb-1.5',
  supplierName:        'font-medium truncate max-w-[65%]',
  supplierRev:         'font-semibold',
  supplierTrack:       'h-2.5 bg-gray-100 rounded-full overflow-hidden',
  supplierFill:        'h-full rounded-full',
  tableWrapper:        'border border-gray-100 rounded-xl overflow-hidden',
  tableEmpty:          'text-sm text-gray-400 text-center py-6',
  thead:               'bg-gray-50',
  th:                  'px-4 py-3 text-left text-xs font-bold text-gray-400 uppercase tracking-wide',
  rowEven:             'bg-white',
  rowOdd:              'bg-gray-50',
  tdRank:              'px-4 py-3 text-gray-400 text-xs font-bold',
  tdName:              'px-4 py-3 font-semibold text-gray-800',
  tdOrders:            'px-4 py-3 text-gray-600',
  tdAmount:            'px-4 py-3 font-bold text-gray-800',
  footer:              'border-t border-gray-100 pt-4 text-center text-xs text-gray-300',
};
