export const styles = {
  loadingWrapper:   'min-h-screen bg-gray-100 flex items-center justify-center',
  spinner:          'w-10 h-10 border-4 border-gray-300 border-t-red-500 rounded-full animate-spin',
  page:             'min-h-screen bg-gray-200 py-8 px-4 print:bg-white print:p-0',
  printBar:         'flex justify-center mb-6 print:hidden',
  printBtn:         'flex items-center gap-2 bg-red-600 hover:bg-red-700 text-white text-sm font-semibold px-6 py-2.5 rounded-lg shadow transition-colors',
  card:             'bg-white w-full max-w-4xl mx-auto shadow-xl rounded-lg overflow-hidden print:shadow-none print:rounded-none print:max-w-none',
  header:           'bg-red-600 px-8 py-6 text-white',
  headerTitle:      'text-2xl font-bold tracking-tight',
  headerSubtitle:   'text-red-200 text-sm mt-1',
  headerDate:       'text-red-300 text-xs mt-1',
  body:             'px-8 py-6 space-y-6',
  summaryGrid:      'grid grid-cols-3 gap-4',
  summaryCardRed:   'border border-gray-100 rounded-xl p-4 bg-red-50',
  summaryCardOrange:'border border-gray-100 rounded-xl p-4 bg-orange-50',
  summaryCardGray:  'border border-gray-100 rounded-xl p-4 bg-gray-50',
  summaryLabelRed:  'text-xs font-semibold text-red-400 uppercase tracking-wide mb-2',
  summaryLabelOrange:'text-xs font-semibold text-orange-400 uppercase tracking-wide mb-2',
  summaryLabelGray: 'text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2',
  summaryValueRed:  'text-3xl font-bold text-red-600',
  summaryValueOrange:'text-3xl font-bold text-orange-500',
  summaryValueGray: 'text-3xl font-bold text-gray-700',
  summaryMetaRed:   'text-xs text-red-400 mt-1',
  summaryMetaOrange:'text-xs text-orange-400 mt-1',
  summaryMetaGray:  'text-xs text-gray-400 mt-1',
  sectionLabel:     'text-xs font-bold text-gray-400 uppercase tracking-widest mb-3',
  tableWrapper:     'border border-gray-100 rounded-xl overflow-hidden',
  table:            'w-full text-sm',
  thead:            'bg-gray-50',
  th:               'px-4 py-3 text-left text-xs font-bold text-gray-400 uppercase tracking-wide',
  rowOut:           'bg-red-50',
  rowEven:          'bg-white',
  rowOdd:           'bg-orange-50/40',
  tdRank:           'px-4 py-3 text-gray-400 text-xs font-bold',
  tdName:           'px-4 py-3 font-medium text-gray-800',
  tdCategory:       'px-4 py-3 text-gray-500',
  tdPrice:          'px-4 py-3 text-gray-600',
  tdQty:            'px-4 py-3 font-bold text-gray-800',
  tdDate:           'px-4 py-3 text-gray-400 text-xs',
  badgeOut:         'inline-block px-2 py-0.5 rounded-full text-xs font-semibold bg-red-100 text-red-700',
  badgeLow:         'inline-block px-2 py-0.5 rounded-full text-xs font-semibold bg-orange-100 text-orange-700',
  emptyCell:        'px-4 py-8 text-center text-green-600 font-medium text-sm',
  footer:           'border-t border-gray-100 pt-4 text-center text-xs text-gray-300',
};
