spring.application.name=ecom
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ecom?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=7f4c9a2e8d6b1c3f5a9e0d2b7c8f4a6d1e3b9c5f7a2d6e8c
jwt.expiration=345600000

server.error.include-message=always